"""
WAF Detection and Fingerprinting Plugin

Detects Web Application Firewalls and provides fingerprinting information.
Identifies WAF vendor, version where possible, and response behaviors.
"""

from plugins.base_plugin import BasePlugin, Finding
from typing import Dict, List, Optional
import re


class WAFDetectionPlugin(BasePlugin):
    """
    Detects WAF presence and identifies the vendor/type.
    Uses multiple detection methods: headers, cookies, response codes, blocking behavior.
    """

    # WAF signatures organized by vendor
    WAF_SIGNATURES = {
        "Cloudflare": {
            "headers": ["CF-RAY", "CF-Cache-Status", "CF-Connecting-IP"],
            "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
            "body_patterns": ["cloudflare", "error 1020", "checking your browser"],
            "block_codes": [403, 503],
        },
        "AWS WAF": {
            "headers": ["X-AMZ-CF-ID", "X-Cache"],
            "cookies": [],
            "body_patterns": ["aws waf", "amazon web services"],
            "block_codes": [403, 503],
        },
        "ModSecurity": {
            "headers": ["ModSecurity", "X-Mod-Security"],
            "cookies": [],
            "body_patterns": ["modsecurity", "not acceptable"],
            "block_codes": [403, 406],
        },
        "Incapsula": {
            "headers": ["X-Iinfo", "X-CDN", "Incapsula"],
            "cookies": ["visid_incap", "incap_ses"],
            "body_patterns": ["incapsula incident", "incapsula resource"],
            "block_codes": [403],
        },
        "Sucuri": {
            "headers": ["X-Sucuri-ID", "X-Sucuri-Cache"],
            "cookies": ["sucuri_cloudproxy_uuid"],
            "body_patterns": ["sucuri website firewall", "access denied"],
            "block_codes": [403],
        },
        "Akamai": {
            "headers": ["X-Akamai-Request-ID", "X-Akamai-Cache", "X-EdgeConnect"],
            "cookies": ["AKA_A2", "AKA_T1"],
            "body_patterns": ["akamai", "reference \\d+"],
            "block_codes": [403, 507],
        },
        "F5 BIG-IP ASM": {
            "headers": ["X-WA-Info", "X-Cnection"],
            "cookies": ["BIGipServer", "TS", "ASINFO"],
            "body_patterns": ["the requested url was rejected", "please consult"],
            "block_codes": [403, 406, 409],
        },
        "Barracuda": {
            "headers": ["X-Barracuda-Local", "X-Barracuda-URL"],
            "cookies": ["barra_counter"],
            "body_patterns": ["barracuda networks", "you have been blocked"],
            "block_codes": [403, 512],
        },
        "Fortinet FortiWeb": {
            "headers": ["X-FW-Info", "X-FortiWeb"],
            "cookies": [],
            "body_patterns": ["fortiweb", "fortinet"],
            "block_codes": [403],
        },
        "Wordfence": {
            "headers": [],
            "cookies": ["wfvt_", "wordfence"],
            "body_patterns": ["wordfence", "generated by wordfence"],
            "block_codes": [403, 503],
        },
        "Sitelock": {
            "headers": ["X-Sitelock-Processing", "X-Sitelock"],
            "cookies": [],
            "body_patterns": ["sitelock", "site is protected"],
            "block_codes": [403],
        },
        "StackPath": {
            "headers": ["X-StackPath-Edge", "X-StackPath"],
            "cookies": ["sp_", "stackpath"],
            "body_patterns": ["stackpath", "please complete the security check"],
            "block_codes": [403],
        },
        "Comodo": {
            "headers": ["X-Comodo-WAF", "X-Comodo"],
            "cookies": [],
            "body_patterns": ["comodo", "protected by comodo"],
            "block_codes": [403],
        },
        "Radware AppWall": {
            "headers": ["X-RW", "X-Radware"],
            "cookies": [],
            "body_patterns": ["unauthorized activity has been detected", "radware"],
            "block_codes": [403, 501],
        },
    }

    # Test payloads that might trigger WAF blocking
    TEST_PAYLOADS = [
        ("<script>alert(1)</script>", "XSS"),
        ("' OR '1'='1", "SQL Injection"),
        ("../../etc/passwd", "Path Traversal"),
        ("<?php echo 'test'; ?>", "PHP Injection"),
        (" UNION SELECT ", "SQL Union"),
    ]

    def get_name(self) -> str:
        return "waf_detection"

    def get_description(self) -> str:
        return "Detects Web Application Firewalls and fingerprints their configuration"

    def _check_headers(self, headers: Dict) -> Dict[str, int]:
        """Check headers for WAF signatures. Returns dict of vendor -> confidence score."""
        scores = {}
        headers_lower = {k.lower(): v for k, v in headers.items()}
        
        for vendor, signatures in self.WAF_SIGNATURES.items():
            score = 0
            for header in signatures["headers"]:
                if header.lower() in headers_lower:
                    score += 2  # Strong indicator
            
            if score > 0:
                scores[vendor] = score
        
        return scores

    def _check_cookies(self, headers: Dict) -> Dict[str, int]:
        """Check cookies for WAF signatures."""
        scores = {}
        cookie_header = headers.get("Set-Cookie", "")
        
        for vendor, signatures in self.WAF_SIGNATURES.items():
            score = 0
            for cookie in signatures["cookies"]:
                if cookie in cookie_header:
                    score += 2
            
            if score > 0:
                scores[vendor] = score
        
        return scores

    def _check_body(self, body: str) -> Dict[str, int]:
        """Check response body for WAF block pages."""
        scores = {}
        body_lower = body.lower() if body else ""
        
        for vendor, signatures in self.WAF_SIGNATURES.items():
            score = 0
            for pattern in signatures["body_patterns"]:
                if re.search(pattern, body_lower, re.IGNORECASE):
                    score += 1
            
            if score > 0:
                scores[vendor] = score
        
        return scores

    def _test_waf_response(self, url: str, request_handler) -> Optional[Dict]:
        """Test WAF by sending suspicious payloads and observing response."""
        triggered_tests = []
        
        for payload, attack_type in self.TEST_PAYLOADS[:2]:  # Limit to first 2 to be polite
            try:
                test_url = f"{url}?test={payload}"
                response = request_handler.get(test_url)
                
                if response:
                    # Check if blocked
                    if response.status_code in [403, 406, 409, 501, 503, 507, 512]:
                        triggered_tests.append({
                            "payload_type": attack_type,
                            "status_code": response.status_code,
                            "blocked": True,
                        })
                    # Check for WAF indicators in response
                    for vendor, sigs in self.WAF_SIGNATURES.items():
                        for pattern in sigs["body_patterns"]:
                            if re.search(pattern, response.text or "", re.IGNORECASE):
                                triggered_tests.append({
                                    "payload_type": attack_type,
                                    "detected_waf": vendor,
                                    "blocked": True,
                                })
                                
            except Exception:
                continue
        
        if triggered_tests:
            return {
                "test_results": triggered_tests,
                "total_tests": len(self.TEST_PAYLOADS[:2]),
                "blocking_detected": True,
            }
        
        return None

    def _calculate_confidence(self, header_score: int, cookie_score: int, body_score: int, test_result: bool) -> str:
        """Calculate overall confidence level."""
        total_score = header_score + cookie_score + body_score
        
        if test_result:
            total_score += 3  # Strong indicator
        
        if total_score >= 5:
            return "high"
        elif total_score >= 3:
            return "medium"
        elif total_score >= 1:
            return "low"
        return "none"

    def scan(self, url_info: Dict, request_handler) -> List[Finding]:
        findings = []
        
        if url_info.get("depth", 0) > 0:
            return findings
        
        url = url_info["url"]
        response = request_handler.get(url)
        if response is None:
            return findings
        
        headers = response.headers
        body = response.text or ""
        
        # Gather evidence
        header_scores = self._check_headers(headers)
        cookie_scores = self._check_cookies(headers)
        body_scores = self._check_body(body)
        
        # Test WAF blocking (only on root URL)
        test_results = self._test_waf_response(url, request_handler)
        
        # Combine scores by vendor
        all_vendors = set(list(header_scores.keys()) + list(cookie_scores.keys()) + list(body_scores.keys()))
        
        detected_wafs = []
        
        for vendor in all_vendors:
            h_score = header_scores.get(vendor, 0)
            c_score = cookie_scores.get(vendor, 0)
            b_score = body_scores.get(vendor, 0)
            tested = test_results is not None and test_results.get("blocking_detected", False)
            
            confidence = self._calculate_confidence(h_score, c_score, b_score, tested)
            
            if confidence != "none":
                detected_wafs.append({
                    "vendor": vendor,
                    "confidence": confidence,
                    "evidence": {
                        "headers": h_score > 0,
                        "cookies": c_score > 0,
                        "body": b_score > 0,
                        "blocking_test": tested,
                    },
                })
        
        # Sort by confidence
        confidence_order = {"high": 0, "medium": 1, "low": 2}
        detected_wafs.sort(key=lambda x: confidence_order.get(x["confidence"], 3))
        
        # Create findings
        for waf in detected_wafs[:3]:  # Top 3 detections
            severity = "info"
            if waf["confidence"] == "high":
                severity = "low"  # WAF presence is good, but we report it
            
            findings.append(
                Finding(
                    plugin_name=self.get_name(),
                    severity=severity,
                    title=f"WAF Detected: {waf['vendor']} ({waf['confidence']} confidence)",
                    description=f"A Web Application Firewall from {waf['vendor']} was detected protecting this application.",
                    url=url,
                    evidence={
                        "waf_vendor": waf["vendor"],
                        "confidence": waf["confidence"],
                        "detection_methods": [k for k, v in waf["evidence"].items() if v],
                    },
                    remediation="Ensure WAF rules are properly tuned to minimize false positives while maintaining security.",
                )
            )
        
        # If no WAF detected and blocking tests passed without blocking, report it
        if not detected_wafs and test_results and not test_results.get("blocking_detected"):
            findings.append(
                Finding(
                    plugin_name=self.get_name(),
                    severity="medium",
                    title="No WAF Detected",
                    description="No Web Application Firewall was detected. Malicious requests were not blocked.",
                    url=url,
                    evidence={
                        "tests_run": test_results["total_tests"],
                        "none_blocked": True,
                    },
                    remediation="Consider implementing a WAF (Cloudflare, AWS WAF, ModSecurity) to protect against common web attacks.",
                )
            )
        
        return findings
